### ISSUE TITLE
Window resizing issues with low scalling

### ISSUE THREAD

**Issue by shivanshvermak** [paulpacifico/shutter-encoder#146]
I have a 14-inch laptop and the window of Shutter Encoder doesn't appear right when maximized. Also it can't be manually resizes as well (to decrease, increasing works). 

https://github.com/paulpacifico/shutter-encoder/assets/15206857/043e3e92-2d60-494f-b9f1-57570d9e70bc

**Comment by paulpacifico** [comment]
Thanks for your feedback, I've corrected this bug for the next release (v17.4) it should be available at the end of this month.

Paul.

**Comment by shivanshvermak** [comment]
It's better in the new version but still isn't fully fixed. 
![image](https://github.com/paulpacifico/shutter-encoder/assets/15206857/b9bb9b40-2c27-4a5b-8cdb-b07398f6c2ae)

**Comment by iffinland** [comment]
Thanks for the good software.
I am using linux AppImage version on Debian 12
 I can't move the window anywhere, half of the window is hidden, i.e. outside the screen

attached video clip

https://github.com/paulpacifico/shutter-encoder/assets/157421268/4d87e252-5fa4-4668-807d-42219ddfe376
