### ISSUE TITLE
Problem showed up on 18.4

### ISSUE THREAD

**Issue by sortakalpuyu** [paulpacifico/shutter-encoder#222]
I was using the program and everything was good. Then i got the update notification and updated. After it install the new version (18.4) videos shows as a full black screen on editing mode. And it doesn't open when i double click to open in player, too. I restarted computer but the problem isn't fixed. I uninstall it and will try to install the 18.3 version again.

Edit: yeah i'm very sad now because installing old version didn't work, too. I don't know what's wrong i will try to reinstall ffmpeg but idk i mean the processing and encoding is works well. I just can't view videos on player or editing mode so i can't cut or crop the video as i want (video is just blackscreen). Here's a screenshot. How can it be solved?

![Screenshot 2024-08-13 175746](https://github.com/user-attachments/assets/467beab6-b288-4678-a9ee-04ec03bd0e8e)

**Comment by paulpacifico** [comment]
Try to set the GPU decoding on '**auto**' or '**none**'.

Paul.

**Comment by sortakalpuyu** [comment]
Today i tried again and magically the problem gone. I didn't do anything and i didn't understand. Anyway i'm glad thanks

**Comment by sortakalpuyu** [comment]
Okay, the same problem occured just now again. Double click just opens the window but the video can't be loading and the window close button isn't working when this happens. Looks like the image belove. And in video edit mode there is just black screen again. Idk what's happening.
![Screenshot 2024-08-22 233205](https://github.com/user-attachments/assets/b4fb0033-da72-4781-a134-a1807551d0b9)

**Comment by sortakalpuyu** [comment]
Today, the problem again solved by itself. Probably it will again occur. Do anyone have any idea why does it become like that?

**Comment by zolero** [comment]
I've got the exact same problem after upgrading, after downgrading to 18.3 the problem still persists. Seems some configuration got altered or mixed up in registry? Also tried setting opengl to false, but still results in a black screen. Starting a conversion works though.

**Comment by BrandonsBakedBeans** [comment]
I have also experienced this issue starting 18.4, and 18.5 same issue. 18.3 is working still.

**Comment by hoja59** [comment]
Exactly the same here from version 18.2
It has to do with the AMD drivers
After an update of the AMD "Adrenaline" drivers the program works.
However, if you restart the computer the problem comes back.
With the AMD "Pro" driver the program works fine here but it is not a nice solution for me.

**Comment by paulpacifico** [comment]
Try to change "-Dsun.java2d.opengl=true" to "-Dsun.java2d.opengl=false" in app shortcut properties

**Comment by hoja59** [comment]
YES it works!!!
Veel dank, tijd voor een nieuwe donatie :-)

![Screenshot 2024-10-24 134256](https://github.com/user-attachments/assets/857b7d35-da60-4539-98b5-9ff79ec4c165)

**Comment by hoja59** [comment]
oops, sorry,
 = Many thanks, time for a new donation :-)
